### ISSUE TITLE
Calling list on repo fails with terrible information

### ISSUE THREAD

**Issue by dohnto** [dohnto/pydor#1]
# How to reproduce
```
pydor list quay.io/etcd
```

# Produces:
```
Traceback (most recent call last):
  File "/usr/local/bin/pydor", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pydor/commandline.py", line 60, in list
    _list(generator, limit, output, insecure)
  File "/usr/local/lib/python2.7/dist-packages/pydor/commandline.py", line 33, in _list
    items = [[n] for n in itertools.islice(generator, limit)]
  File "/usr/local/lib/python2.7/dist-packages/pydor/api.py", line 127, in next
    self.cache = collections.deque(response.json()[self.entity.response_key])
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 793, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

# Expected: some sane information that list is meant for registry only

**Comment by FUSAKLA** [comment]
This is terrible :scream:
