### ISSUE TITLE
ImportError: cannot import name 'API'

### ISSUE THREAD

**Issue by cdxujing** [dohnto/pydor#6]
Traceback (most recent call last):
  File "/home/jing/.local/bin/pydor", line 7, in <module>
    from pydor.commandline import cli
  File "/home/jing/.local/lib/python3.6/site-packages/pydor/__init__.py", line 1, in <module>
    from api import API
ImportError: cannot import name 'API'

**Comment by dohnto** [comment]
Reproduced, created CI in order to prevent it in future: https://github.com/dohnto/pydor/pull/7

**Comment by dohnto** [comment]
Feel free to reopen the issue if neccessary.
